export type Country = {
  code: string
  name: string
  nameIt: string
  region: string
  searchTerms: string[]
}

export const COUNTRIES: Country[] = [
  // Europa
  { code: 'IT', name: 'Italy', nameIt: 'Italia', region: 'europa', searchTerms: ['italy', 'italian', 'rome', 'milan', 'meloni'] },
  { code: 'FR', name: 'France', nameIt: 'Francia', region: 'europa', searchTerms: ['france', 'french', 'paris', 'macron'] },
  { code: 'DE', name: 'Germany', nameIt: 'Germania', region: 'europa', searchTerms: ['germany', 'german', 'berlin', 'scholz'] },
  { code: 'ES', name: 'Spain', nameIt: 'Spagna', region: 'europa', searchTerms: ['spain', 'spanish', 'madrid', 'sanchez'] },
  { code: 'PT', name: 'Portugal', nameIt: 'Portogallo', region: 'europa', searchTerms: ['portugal', 'portuguese', 'lisbon'] },
  { code: 'GB', name: 'United Kingdom', nameIt: 'Regno Unito', region: 'europa', searchTerms: ['uk', 'britain', 'london', 'starmer'] },
  { code: 'NL', name: 'Netherlands', nameIt: 'Olanda', region: 'europa', searchTerms: ['netherlands', 'dutch', 'amsterdam'] },
  { code: 'BE', name: 'Belgium', nameIt: 'Belgio', region: 'europa', searchTerms: ['belgium', 'belgian', 'brussels'] },
  { code: 'CH', name: 'Switzerland', nameIt: 'Svizzera', region: 'europa', searchTerms: ['switzerland', 'swiss', 'zurich'] },
  { code: 'AT', name: 'Austria', nameIt: 'Austria', region: 'europa', searchTerms: ['austria', 'austrian', 'vienna'] },
  { code: 'SE', name: 'Sweden', nameIt: 'Svezia', region: 'europa', searchTerms: ['sweden', 'swedish', 'stockholm'] },
  { code: 'NO', name: 'Norway', nameIt: 'Norvegia', region: 'europa', searchTerms: ['norway', 'norwegian', 'oslo'] },
  { code: 'DK', name: 'Denmark', nameIt: 'Danimarca', region: 'europa', searchTerms: ['denmark', 'danish', 'copenhagen'] },
  { code: 'FI', name: 'Finland', nameIt: 'Finlandia', region: 'europa', searchTerms: ['finland', 'finnish', 'helsinki'] },
  { code: 'PL', name: 'Poland', nameIt: 'Polonia', region: 'europa', searchTerms: ['poland', 'polish', 'warsaw'] },
  { code: 'CZ', name: 'Czech Republic', nameIt: 'Rep. Ceca', region: 'europa', searchTerms: ['czech', 'prague'] },
  { code: 'HU', name: 'Hungary', nameIt: 'Ungheria', region: 'europa', searchTerms: ['hungary', 'hungarian', 'budapest', 'orban'] },
  { code: 'RO', name: 'Romania', nameIt: 'Romania', region: 'europa', searchTerms: ['romania', 'romanian', 'bucharest'] },
  { code: 'GR', name: 'Greece', nameIt: 'Grecia', region: 'europa', searchTerms: ['greece', 'greek', 'athens'] },
  { code: 'RU', name: 'Russia', nameIt: 'Russia', region: 'europa', searchTerms: ['russia', 'russian', 'moscow', 'putin', 'kremlin'] },
  { code: 'UA', name: 'Ukraine', nameIt: 'Ucraina', region: 'europa', searchTerms: ['ukraine', 'ukrainian', 'kyiv', 'zelensky'] },
  { code: 'TR', name: 'Turkey', nameIt: 'Turchia', region: 'europa', searchTerms: ['turkey', 'turkish', 'ankara', 'erdogan'] },
  { code: 'HR', name: 'Croatia', nameIt: 'Croazia', region: 'europa', searchTerms: ['croatia', 'croatian', 'zagreb'] },
  { code: 'RS', name: 'Serbia', nameIt: 'Serbia', region: 'europa', searchTerms: ['serbia', 'serbian', 'belgrade'] },
  { code: 'SK', name: 'Slovakia', nameIt: 'Slovacchia', region: 'europa', searchTerms: ['slovakia', 'slovak', 'bratislava'] },
  { code: 'BG', name: 'Bulgaria', nameIt: 'Bulgaria', region: 'europa', searchTerms: ['bulgaria', 'bulgarian', 'sofia'] },
  { code: 'BY', name: 'Belarus', nameIt: 'Bielorussia', region: 'europa', searchTerms: ['belarus', 'belarusian', 'minsk', 'lukashenko'] },
  // Americhe
  { code: 'US', name: 'United States', nameIt: 'USA', region: 'americhe', searchTerms: ['united states', 'usa', 'american', 'washington', 'trump', 'biden'] },
  { code: 'CA', name: 'Canada', nameIt: 'Canada', region: 'americhe', searchTerms: ['canada', 'canadian', 'ottawa', 'trudeau'] },
  { code: 'MX', name: 'Mexico', nameIt: 'Messico', region: 'americhe', searchTerms: ['mexico', 'mexican', 'mexico city'] },
  { code: 'BR', name: 'Brazil', nameIt: 'Brasile', region: 'americhe', searchTerms: ['brazil', 'brazilian', 'brasilia', 'lula'] },
  { code: 'AR', name: 'Argentina', nameIt: 'Argentina', region: 'americhe', searchTerms: ['argentina', 'argentine', 'buenos aires', 'milei'] },
  { code: 'CL', name: 'Chile', nameIt: 'Cile', region: 'americhe', searchTerms: ['chile', 'chilean', 'santiago'] },
  { code: 'CO', name: 'Colombia', nameIt: 'Colombia', region: 'americhe', searchTerms: ['colombia', 'colombian', 'bogota'] },
  { code: 'PE', name: 'Peru', nameIt: 'Peru', region: 'americhe', searchTerms: ['peru', 'peruvian', 'lima'] },
  { code: 'VE', name: 'Venezuela', nameIt: 'Venezuela', region: 'americhe', searchTerms: ['venezuela', 'venezuelan', 'caracas', 'maduro'] },
  { code: 'CU', name: 'Cuba', nameIt: 'Cuba', region: 'americhe', searchTerms: ['cuba', 'cuban', 'havana'] },
  { code: 'EC', name: 'Ecuador', nameIt: 'Ecuador', region: 'americhe', searchTerms: ['ecuador', 'ecuadorian', 'quito'] },
  { code: 'BO', name: 'Bolivia', nameIt: 'Bolivia', region: 'americhe', searchTerms: ['bolivia', 'bolivian', 'la paz'] },
  { code: 'PY', name: 'Paraguay', nameIt: 'Paraguay', region: 'americhe', searchTerms: ['paraguay', 'paraguayan', 'asuncion'] },
  { code: 'UY', name: 'Uruguay', nameIt: 'Uruguay', region: 'americhe', searchTerms: ['uruguay', 'uruguayan', 'montevideo'] },
  // Medio Oriente
  { code: 'IL', name: 'Israel', nameIt: 'Israele', region: 'medio-oriente', searchTerms: ['israel', 'israeli', 'tel aviv', 'netanyahu'] },
  { code: 'PS', name: 'Palestine', nameIt: 'Palestina', region: 'medio-oriente', searchTerms: ['palestine', 'palestinian', 'gaza', 'west bank', 'hamas'] },
  { code: 'IR', name: 'Iran', nameIt: 'Iran', region: 'medio-oriente', searchTerms: ['iran', 'iranian', 'tehran', 'khamenei'] },
  { code: 'SA', name: 'Saudi Arabia', nameIt: 'Arabia Saudita', region: 'medio-oriente', searchTerms: ['saudi arabia', 'saudi', 'riyadh', 'mbs'] },
  { code: 'IQ', name: 'Iraq', nameIt: 'Iraq', region: 'medio-oriente', searchTerms: ['iraq', 'iraqi', 'baghdad'] },
  { code: 'SY', name: 'Syria', nameIt: 'Siria', region: 'medio-oriente', searchTerms: ['syria', 'syrian', 'damascus'] },
  { code: 'LB', name: 'Lebanon', nameIt: 'Libano', region: 'medio-oriente', searchTerms: ['lebanon', 'lebanese', 'beirut', 'hezbollah'] },
  { code: 'JO', name: 'Jordan', nameIt: 'Giordania', region: 'medio-oriente', searchTerms: ['jordan', 'jordanian', 'amman'] },
  { code: 'AE', name: 'UAE', nameIt: 'Emirati Arabi', region: 'medio-oriente', searchTerms: ['uae', 'emirates', 'dubai', 'abu dhabi'] },
  { code: 'QA', name: 'Qatar', nameIt: 'Qatar', region: 'medio-oriente', searchTerms: ['qatar', 'qatari', 'doha'] },
  { code: 'KW', name: 'Kuwait', nameIt: 'Kuwait', region: 'medio-oriente', searchTerms: ['kuwait', 'kuwaiti'] },
  { code: 'YE', name: 'Yemen', nameIt: 'Yemen', region: 'medio-oriente', searchTerms: ['yemen', 'yemeni', 'sanaa', 'houthi'] },
  { code: 'AF', name: 'Afghanistan', nameIt: 'Afghanistan', region: 'medio-oriente', searchTerms: ['afghanistan', 'afghan', 'kabul', 'taliban'] },
  // Asia
  { code: 'CN', name: 'China', nameIt: 'Cina', region: 'asia', searchTerms: ['china', 'chinese', 'beijing', 'xi jinping'] },
  { code: 'JP', name: 'Japan', nameIt: 'Giappone', region: 'asia', searchTerms: ['japan', 'japanese', 'tokyo'] },
  { code: 'IN', name: 'India', nameIt: 'India', region: 'asia', searchTerms: ['india', 'indian', 'new delhi', 'modi'] },
  { code: 'KR', name: 'South Korea', nameIt: 'Corea del Sud', region: 'asia', searchTerms: ['south korea', 'korean', 'seoul'] },
  { code: 'KP', name: 'North Korea', nameIt: 'Corea del Nord', region: 'asia', searchTerms: ['north korea', 'kim jong', 'pyongyang'] },
  { code: 'PK', name: 'Pakistan', nameIt: 'Pakistan', region: 'asia', searchTerms: ['pakistan', 'pakistani', 'islamabad'] },
  { code: 'BD', name: 'Bangladesh', nameIt: 'Bangladesh', region: 'asia', searchTerms: ['bangladesh', 'bangladeshi', 'dhaka'] },
  { code: 'TW', name: 'Taiwan', nameIt: 'Taiwan', region: 'asia', searchTerms: ['taiwan', 'taiwanese', 'taipei'] },
  { code: 'TH', name: 'Thailand', nameIt: 'Thailandia', region: 'asia', searchTerms: ['thailand', 'thai', 'bangkok'] },
  { code: 'VN', name: 'Vietnam', nameIt: 'Vietnam', region: 'asia', searchTerms: ['vietnam', 'vietnamese', 'hanoi'] },
  { code: 'ID', name: 'Indonesia', nameIt: 'Indonesia', region: 'asia', searchTerms: ['indonesia', 'indonesian', 'jakarta'] },
  { code: 'PH', name: 'Philippines', nameIt: 'Filippine', region: 'asia', searchTerms: ['philippines', 'filipino', 'manila'] },
  { code: 'MY', name: 'Malaysia', nameIt: 'Malaysia', region: 'asia', searchTerms: ['malaysia', 'malaysian', 'kuala lumpur'] },
  { code: 'SG', name: 'Singapore', nameIt: 'Singapore', region: 'asia', searchTerms: ['singapore', 'singaporean'] },
  { code: 'MM', name: 'Myanmar', nameIt: 'Myanmar', region: 'asia', searchTerms: ['myanmar', 'burma', 'yangon'] },
  { code: 'KZ', name: 'Kazakhstan', nameIt: 'Kazakistan', region: 'asia', searchTerms: ['kazakhstan', 'kazakh', 'astana'] },
  { code: 'UZ', name: 'Uzbekistan', nameIt: 'Uzbekistan', region: 'asia', searchTerms: ['uzbekistan', 'uzbek', 'tashkent'] },
  // Africa
  { code: 'NG', name: 'Nigeria', nameIt: 'Nigeria', region: 'africa', searchTerms: ['nigeria', 'nigerian', 'lagos', 'abuja'] },
  { code: 'EG', name: 'Egypt', nameIt: 'Egitto', region: 'africa', searchTerms: ['egypt', 'egyptian', 'cairo'] },
  { code: 'ZA', name: 'South Africa', nameIt: 'Sudafrica', region: 'africa', searchTerms: ['south africa', 'south african', 'johannesburg', 'pretoria'] },
  { code: 'ET', name: 'Ethiopia', nameIt: 'Etiopia', region: 'africa', searchTerms: ['ethiopia', 'ethiopian', 'addis ababa'] },
  { code: 'KE', name: 'Kenya', nameIt: 'Kenya', region: 'africa', searchTerms: ['kenya', 'kenyan', 'nairobi'] },
  { code: 'TZ', name: 'Tanzania', nameIt: 'Tanzania', region: 'africa', searchTerms: ['tanzania', 'tanzanian', 'dar es salaam'] },
  { code: 'GH', name: 'Ghana', nameIt: 'Ghana', region: 'africa', searchTerms: ['ghana', 'ghanaian', 'accra'] },
  { code: 'MA', name: 'Morocco', nameIt: 'Marocco', region: 'africa', searchTerms: ['morocco', 'moroccan', 'rabat', 'casablanca'] },
  { code: 'DZ', name: 'Algeria', nameIt: 'Algeria', region: 'africa', searchTerms: ['algeria', 'algerian', 'algiers'] },
  { code: 'SD', name: 'Sudan', nameIt: 'Sudan', region: 'africa', searchTerms: ['sudan', 'sudanese', 'khartoum'] },
  { code: 'LY', name: 'Libya', nameIt: 'Libia', region: 'africa', searchTerms: ['libya', 'libyan', 'tripoli'] },
  { code: 'SO', name: 'Somalia', nameIt: 'Somalia', region: 'africa', searchTerms: ['somalia', 'somali', 'mogadishu'] },
  { code: 'CD', name: 'Congo (DRC)', nameIt: 'Congo (RDC)', region: 'africa', searchTerms: ['congo', 'drc', 'kinshasa'] },
  { code: 'ZW', name: 'Zimbabwe', nameIt: 'Zimbabwe', region: 'africa', searchTerms: ['zimbabwe', 'zimbabwean', 'harare'] },
  { code: 'SN', name: 'Senegal', nameIt: 'Senegal', region: 'africa', searchTerms: ['senegal', 'senegalese', 'dakar'] },
  { code: 'TN', name: 'Tunisia', nameIt: 'Tunisia', region: 'africa', searchTerms: ['tunisia', 'tunisian', 'tunis'] },
  // Oceania
  { code: 'AU', name: 'Australia', nameIt: 'Australia', region: 'oceania', searchTerms: ['australia', 'australian', 'canberra', 'sydney'] },
  { code: 'NZ', name: 'New Zealand', nameIt: 'Nuova Zelanda', region: 'oceania', searchTerms: ['new zealand', 'kiwi', 'wellington', 'auckland'] },
  { code: 'PG', name: 'Papua New Guinea', nameIt: 'Papua N. Guinea', region: 'oceania', searchTerms: ['papua', 'port moresby'] },
  { code: 'FJ', name: 'Fiji', nameIt: 'Figi', region: 'oceania', searchTerms: ['fiji', 'fijian', 'suva'] },
]

export const REGION_LABELS: Record<string, string> = {
  'europa':        'Europa',
  'americhe':      'Americhe',
  'medio-oriente': 'Medio Oriente',
  'asia':          'Asia',
  'africa':        'Africa',
  'oceania':       'Oceania',
}
