// Feed RSS italiani aggiuntivi — espansione 2026-05-16
// Solo URL con pattern RSS confermato (.xml, /feed/, /rss/, feedburner, feedpress,
// gelocal/rss, _rss). Le homepage non-RSS dell'elenco utente sono state escluse
// perche' rss-parser fallirebbe su HTML.
import type { FeedMeta } from './rss'

export const ITALIAN_FEEDS: FeedMeta[] = [

  // ─── AGENZIE & MAINSTREAM (nazionali) ────────────────────────────────────
  { id: 'wikinews_it',      source: 'Wikinews Italia',          url: 'http://feeds2.feedburner.com/WikinewsUltimeNotizie',                            country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 7.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'famiglia_cristi',  source: 'Famiglia Cristiana',       url: 'http://www.famigliacristiana.it/_rss/di-cosa-parliamo--articoli.aspx',          country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center',       reliability: 7.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'repubblica_home',  source: 'la Repubblica',            url: 'http://www.repubblica.it/rss/homepage/rss2.0.xml',                              country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-left',  reliability: 8.2, aiValue: 'high',   antiBiasValue: 'high', scope: 'national' },
  { id: 'ansa_generale',    source: 'ANSA Generale',            url: 'http://www.ansa.it/sito/ansait_rss.xml',                                        country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center',       reliability: 8.5, aiValue: 'high',   antiBiasValue: 'high', scope: 'national' },
  { id: 'iltempo_cronaca',  source: 'Il Tempo',                 url: 'https://www.iltempo.it/rss.jsp?sezione=108',                                    country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 7.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },

  // ─── ANSA Europa / Politica estera ────────────────────────────────────────
  { id: 'ansa_europa',      source: 'ANSA Europa',              url: 'https://www.ansa.it/europa/notizie/rss.xml',                                    country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center',       reliability: 8.5, aiValue: 'high',   antiBiasValue: 'high', scope: 'national' },
  { id: 'ansa_europarl',    source: 'ANSA Europarlamento',      url: 'https://www.ansa.it/europa/notizie/europarlamento/news/europarlamento_rss.xml', country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center',       reliability: 8.5, aiValue: 'high',   antiBiasValue: 'high', scope: 'national' },

  // ─── TECNOLOGIA ──────────────────────────────────────────────────────────
  { id: 'sole_tech',        source: 'Il Sole 24 Ore Tecnologia',url: 'https://www.ilsole24ore.com/rss/tecnologia.xml',                                country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.4, aiValue: 'high',   antiBiasValue: 'high', scope: 'national' },
  { id: 'internetto',       source: 'Internetto',               url: 'https://internetto.it/feed/',                                                   country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 7.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'androidiani',      source: 'Androidiani',              url: 'http://feeds.feedburner.com/Androidiani',                                       country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 6.8, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'spaziogames',      source: 'SpazioGames',              url: 'https://www.spaziogames.it/docs/feed/news.xml',                                 country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 7.2, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'whatstech',        source: "What's Tech",              url: 'https://whatstech.it/feed/',                                                    country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 6.8, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'fsf_news',         source: 'Free Software Foundation', url: 'https://www.fsf.org/static/fsforg/rss/news.xml',                                country: 'USA',   region: 'americhe', type: 'independent', bias: 'center-left',  reliability: 8.5, aiValue: 'medium', antiBiasValue: 'high', scope: 'national' },
  { id: 'linux_journal',    source: 'Linux Journal',            url: 'https://www.linuxjournal.com/node/feed',                                        country: 'USA',   region: 'americhe', type: 'independent', bias: 'center',       reliability: 8.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'nintendo_life',    source: 'Nintendo Life',            url: 'http://www.nintendolife.com/feeds/latest',                                      country: 'UK',    region: 'europa', type: 'independent',   bias: 'center',       reliability: 7.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },

  // ─── SPORT ───────────────────────────────────────────────────────────────
  { id: 'gazzetta_home',    source: 'La Gazzetta dello Sport',  url: 'https://www.gazzetta.it/rss/home.xml',                                          country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center',       reliability: 8.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'sole_sport',       source: 'Il Sole 24 Ore Sport',     url: 'https://www.ilsole24ore.com/rss/sport24.xml',                                   country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },

  // ─── SCIENZA / SALUTE ────────────────────────────────────────────────────
  { id: 'sole_salute',      source: 'Il Sole 24 Ore Salute',    url: 'https://www.ilsole24ore.com/rss/salute.xml',                                    country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.4, aiValue: 'high',   antiBiasValue: 'high', scope: 'national' },
  { id: 'oggi_scienza',     source: 'OggiScienza',              url: 'https://oggiscienza.it/feed/',                                                  country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 7.8, aiValue: 'high',   antiBiasValue: 'high', scope: 'national' },
  { id: 'sapere_scienza',   source: 'Sapere Scienza',           url: 'http://www.saperescienza.it/rss-saperescienza',                                 country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 7.5, aiValue: 'high',   antiBiasValue: 'medium', scope: 'national' },

  // ─── ECONOMIA ────────────────────────────────────────────────────────────
  { id: 'sole_finanza',     source: 'Il Sole 24 Ore Finanza',   url: 'https://www.ilsole24ore.com/rss/finanza.xml',                                   country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.5, aiValue: 'high',   antiBiasValue: 'high', scope: 'national' },
  { id: 'sole_tributi',     source: 'Il Sole 24 Ore Norme',     url: 'https://www.ilsole24ore.com/rss/norme-e-tributi.xml',                           country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.4, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'sole_risparmio',   source: 'Il Sole 24 Ore Risparmio', url: 'https://www.ilsole24ore.com/rss/risparmio.xml',                                 country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },

  // ─── ARTE / MODA / CULTURA ───────────────────────────────────────────────
  { id: 'sole_cultura',     source: 'Il Sole 24 Ore Cultura',   url: 'https://www.ilsole24ore.com/rss/cultura.xml',                                   country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.2, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'sole_moda',        source: 'Il Sole 24 Ore Moda',      url: 'https://www.ilsole24ore.com/rss/moda.xml',                                      country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 7.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'sole_arteconomy',  source: 'Il Sole 24 Ore Arteconomy',url: 'https://www.ilsole24ore.com/rss/arteconomy.xml',                                country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_cultura_v2',  source: 'ANSA Cultura',             url: 'http://www.ansa.it/sito/notizie/cultura/cultura_rss.xml',                       country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center',       reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },

  // ─── MUSICA ──────────────────────────────────────────────────────────────
  { id: 'musicoff',         source: 'Musicoff',                 url: 'https://www.musicoff.com/feeds',                                                country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },

  // ─── GASTRONOMIA ─────────────────────────────────────────────────────────
  { id: 'giallo_zaffer',    source: 'GialloZafferano',          url: 'https://www.giallozafferano.it/ricerca-ricette/rss/',                           country: 'Italy', region: 'europa', type: 'independent',   bias: 'center',       reliability: 7.0, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'sole_food',        source: 'Il Sole 24 Ore Food',      url: 'https://www.ilsole24ore.com/rss/food.xml',                                      country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 7.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },

  // ─── VIAGGI ──────────────────────────────────────────────────────────────
  { id: 'sole_viaggi',      source: 'Il Sole 24 Ore Viaggi',    url: 'https://www.ilsole24ore.com/rss/viaggi.xml',                                    country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 7.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },

  // ─── AMBIENTE ────────────────────────────────────────────────────────────
  { id: 'ansa_terragusto',  source: 'ANSA Terra & Gusto',       url: 'https://www.ansa.it/canale_terraegusto/notizie/terraegusto_rss.xml',            country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center',       reliability: 8.2, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'sole_management',  source: 'Il Sole 24 Ore Management',url: 'https://www.ilsole24ore.com/rss/management.xml',                                country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 8.0, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'sole_commenti',    source: 'Il Sole 24 Ore Commenti',  url: 'https://www.ilsole24ore.com/rss/commenti.xml',                                  country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-right', reliability: 7.8, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },

  // ─── ANSA REGIONALI (20 regioni) ─────────────────────────────────────────
  { id: 'ansa_abruzzo',     source: 'ANSA Abruzzo',             url: 'https://www.ansa.it/abruzzo/notizie/abruzzo_rss.xml',                           country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_basilicata',  source: 'ANSA Basilicata',          url: 'https://www.ansa.it/basilicata/notizie/basilicata_rss.xml',                     country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_calabria',    source: 'ANSA Calabria',            url: 'https://www.ansa.it/calabria/notizie/calabria_rss.xml',                         country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_campania',    source: 'ANSA Campania',            url: 'https://www.ansa.it/campania/notizie/campania_rss.xml',                         country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_emilia',      source: 'ANSA Emilia-Romagna',      url: 'https://www.ansa.it/emiliaromagna/notizie/emiliaromagna_rss.xml',               country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_fvg',         source: 'ANSA Friuli Venezia Giulia',url:'https://www.ansa.it/friuliveneziagiulia/notizie/friuliveneziagiulia_rss.xml',   country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_lazio',       source: 'ANSA Lazio',               url: 'https://www.ansa.it/lazio/notizie/lazio_rss.xml',                               country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_liguria',     source: 'ANSA Liguria',             url: 'https://www.ansa.it/liguria/notizie/liguria_rss.xml',                           country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_lombardia',   source: 'ANSA Lombardia',           url: 'https://www.ansa.it/lombardia/notizie/lombardia_rss.xml',                       country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_marche',      source: 'ANSA Marche',              url: 'https://www.ansa.it/marche/notizie/marche_rss.xml',                             country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_molise',      source: 'ANSA Molise',              url: 'https://www.ansa.it/molise/notizie/molise_rss.xml',                             country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_piemonte',    source: 'ANSA Piemonte',            url: 'https://www.ansa.it/piemonte/notizie/piemonte_rss.xml',                         country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_puglia',      source: 'ANSA Puglia',              url: 'https://www.ansa.it/puglia/notizie/puglia_rss.xml',                             country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_sardegna',    source: 'ANSA Sardegna',            url: 'https://www.ansa.it/sardegna/notizie/sardegna_rss.xml',                         country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_sicilia',     source: 'ANSA Sicilia',             url: 'https://www.ansa.it/sicilia/notizie/sicilia_rss.xml',                           country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_toscana',     source: 'ANSA Toscana',             url: 'https://www.ansa.it/toscana/notizie/toscana_rss.xml',                           country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_trentino',    source: 'ANSA Trentino',            url: 'https://www.ansa.it/trentino/notizie/trentino_rss.xml',                         country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_umbria',      source: 'ANSA Umbria',              url: 'https://www.ansa.it/umbria/notizie/umbria_rss.xml',                             country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_vda',         source: "ANSA Valle d'Aosta",       url: 'https://www.ansa.it/valledaosta/notizie/valledaosta_rss.xml',                   country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'ansa_veneto',      source: 'ANSA Veneto',              url: 'https://www.ansa.it/veneto/notizie/veneto_rss.xml',                             country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 8.3, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },

  // ─── REGIONALI LOCALI (con RSS confermato) ───────────────────────────────
  { id: 'pescara_post',     source: 'Pescara Post',             url: 'https://www.pescarapost.it/cronaca/feed/',                                      country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'emmelle',          source: 'Emmelle Notizie',          url: 'https://www.emmelle.it/Rss/Notizie/',                                           country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'crotone_news',     source: 'Crotone News',             url: 'https://www.crotonenews.com/feed',                                              country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'corigliano',       source: 'Corigliano Informa',       url: 'http://www.coriglianoinforma.it/RSSGLOBAL.xml',                                 country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.0, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'ilquaderno',       source: 'Il Quaderno',              url: 'https://www.ilquaderno.it/rss.xml',                                             country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'citta_salerno',    source: 'La Città di Salerno',      url: 'https://www.lacittadisalerno.it/feed-rss',                                      country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 7.0, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'ottopagine',       source: 'Ottopagine',               url: 'https://www.ottopagine.it/feed/',                                               country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'lanuova_ferrara',  source: 'La Nuova Ferrara',         url: 'https://lanuovaferrara.gelocal.it/rss/home',                                    country: 'Italy', region: 'europa', type: 'local',         bias: 'center-left', reliability: 7.2, aiValue: 'low', antiBiasValue: 'low', scope: 'national' },
  { id: 'bologna_rep',      source: 'la Repubblica Bologna',    url: 'https://bologna.repubblica.it/rss/rss2.0.xml',                                  country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-left', reliability: 7.8, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'gazzetta_modena',  source: 'Gazzetta di Modena',       url: 'https://gazzettadimodena.gelocal.it/rss/home',                                  country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 7.0, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'newsrimini',       source: 'NewsRimini',               url: 'http://www.newsrimini.it/feed/',                                                country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'ilfriuli',         source: 'Il Friuli',                url: 'https://www.ilfriuli.it/rss',                                                   country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 7.2, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'ilpiccolo_trieste',source: 'Il Piccolo (Trieste)',     url: 'https://ilpiccolo.gelocal.it/rss/home',                                         country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 7.5, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'abitare_roma',     source: 'Abitare a Roma',           url: 'https://abitarearoma.it/feed',                                                  country: 'Italy', region: 'europa', type: 'local',         bias: 'center-left', reliability: 6.0, aiValue: 'low', antiBiasValue: 'low', scope: 'national' },
  { id: 'roma_provincia',   source: 'Roma Notizie Provincia',   url: 'http://feeds.feedburner.com/romanotizie/provincia',                             country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'roma_notizie',     source: 'Roma Notizie',             url: 'http://feeds.feedburner.com/romanotizie',                                       country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'maceratesi',       source: 'Cronache Maceratesi',      url: 'http://feeds.feedburner.com/cronache_maceratesi',                               country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'cronache_fermane', source: 'Cronache Fermane',         url: 'https://www.cronachefermane.it/feed',                                           country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'cronache_picene',  source: 'Cronache Picene',          url: 'https://www.cronachepicene.it/feed',                                            country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'vivere_fermo',     source: 'Vivere Fermo',             url: 'http://feedproxy.google.com/viverefermo',                                       country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'isnews_molise',    source: 'IsNews Molise',            url: 'https://www.isnews.it/ed-locali/campobasso.feed?type=rss',                      country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'qp_piemonte',      source: 'Quotidiano Piemontese',    url: 'http://feeds.quotidianopiemontese.it/qp/qp-home',                               country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 7.0, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'torino_rep',       source: 'la Repubblica Torino',     url: 'https://torino.repubblica.it/rss/rss2.0.xml',                                   country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-left', reliability: 7.8, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'parchipiemonte',   source: 'Piemonte Parchi',          url: 'http://www.piemonteparchi.it/cms/index.php/feed',                               country: 'Italy', region: 'europa', type: 'government',    bias: 'center', reliability: 7.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'bari_rep',         source: 'la Repubblica Bari',       url: 'https://bari.repubblica.it/dettaglio/feed-rss/1280265',                         country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center-left', reliability: 7.5, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'barletta',         source: 'Barletta Live',            url: 'https://www.barlettalive.it/news/feedrss',                                      country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'mattino_foggia',   source: 'Il Mattino di Foggia',     url: 'https://www.ilmattinodifoggia.it/sezioni/268/rss',                              country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'lasicilia',        source: 'La Sicilia',               url: 'https://www.lasicilia.it/rss.jsp?sezione=108',                                  country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 7.5, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'livesicilia_pa',   source: 'LiveSicilia Palermo',      url: 'http://feeds.feedburner.com/Agrigento-LiveSicilia',                             country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'gds_sicilia',      source: 'Giornale di Sicilia',      url: 'https://feedpress.me/gds_hp_sicilia',                                           country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 7.5, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'gsud_calabria',    source: 'Gazzetta del Sud Calabria',url: 'https://feedpress.me/gsud_hp_calabria',                                         country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 7.5, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'altoadige',        source: 'Alto Adige',               url: 'https://www.altoadige.it/feed-rss',                                             country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 7.5, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'giornaletrentino', source: 'Giornale del Trentino',    url: 'https://www.giornaletrentino.it/feed-rss',                                      country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 7.5, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'msg_veneto',       source: 'Messaggero Veneto',        url: 'https://messaggeroveneto.gelocal.it/rss/home',                                  country: 'Italy', region: 'europa', type: 'mainstream',    bias: 'center', reliability: 7.5, aiValue: 'medium', antiBiasValue: 'medium', scope: 'national' },
  { id: 'oggi_treviso',     source: 'Oggi Treviso',             url: 'https://www.oggitreviso.it/feed_prima_pagina_tutte_le_news',                    country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'padova_rss',       source: 'PadovaNet',                url: 'https://www.padovanet.it/informazione/servizio-rss-di-padovanet',               country: 'Italy', region: 'europa', type: 'government',    bias: 'center', reliability: 7.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'savona_news',      source: 'Savona News',              url: 'http://www.savonanews.it/links/rss/argomenti/savonanewsit/rss.xml',             country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'sanremo_news',     source: 'Sanremo News',             url: 'http://www.sanremonews.it/links/rss/argomenti/sanremonewsit/rss.xml',           country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'imperia_news',     source: 'Imperia News',             url: 'http://www.imperianews.it/links/rss/argomenti/imperianewsit/rss.xml',           country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'voce_genova',      source: 'La Voce di Genova',        url: 'http://www.lavocedigenova.it/links/rss/argomenti/lavocedigenovait/rss.xml',     country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'torinoggi',        source: 'Torino Oggi',              url: 'http://www.torinoggi.it/links/rss/argomenti/torinoggiit/rss.xml',               country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.8, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
  { id: 'fiviereggiogiornale',source: 'Vostro Giornale',        url: 'http://feeds.feedburner.com/il-vostro-giornale-cronaca/',                       country: 'Italy', region: 'europa', type: 'local',         bias: 'center', reliability: 6.5, aiValue: 'low',    antiBiasValue: 'low', scope: 'national' },
]
