import PageLayout from '../../../components/page-layout'
import { IconAlert } from '../../../components/icons'

export const metadata = {
  title: 'Terms of Service — Lens Veritas',
  description: 'Terms and conditions of use for Lens Veritas',
}

const LAST_UPDATED = 'May 15, 2026'

export default function TermsPageEN() {
  return (
    <PageLayout>
      <div className="max-w-3xl mx-auto px-4 py-12">

        <div className="mb-10">
          <h1 className="text-3xl font-bold mb-2" style={{ fontFamily: 'var(--font-h)', color: 'var(--text)' }}>
            Terms of Service
          </h1>
          <p className="text-sm" style={{ color: 'var(--text-3)' }}>
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        {/* Banner versione multilingua + clausola "authoritative version" */}
        <div
          className="mb-8 rounded-lg p-3 text-xs flex items-center justify-between gap-3"
          style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', color: 'var(--text-2)' }}
        >
          <span>This document is also available in Italian.</span>
          <a href="/terms" className="underline shrink-0 hover:opacity-80" style={{ color: 'var(--accent)' }}>
            Versione italiana →
          </a>
        </div>
        <div
          className="mb-10 rounded-lg p-3 text-[11px] leading-relaxed"
          style={{ background: 'rgba(234,179,8,0.06)', border: '1px solid rgba(234,179,8,0.2)', color: 'var(--text-2)' }}
        >
          <strong style={{ color: 'var(--text)' }}>Authoritative version.</strong> This English translation is provided for convenience. The Italian version of this document remains the legally authoritative text. In case of any discrepancy between the two versions, the Italian version shall prevail.
        </div>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: 'var(--text-2)' }}>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text)' }}>1. Description of the service</h2>
            <p>
              Lens Veritas (<strong>lensveritas.com</strong>) is a global news aggregator with AI anti-bias analysis. The service is operated on a personal, non-commercial basis by Paolo Fantinel. Lens Veritas aggregates headlines and content from third-party sources (NewsAPI, The Guardian, GNews, GDELT, RSS feeds) and uses artificial intelligence models (Anthropic Claude, Google Gemini) to produce concise editorial analyses.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text)' }}>2. Acceptance of terms</h2>
            <p>
              By accessing or using Lens Veritas you accept these Terms of Service. If you do not accept, please do not use the service. Continued use after any changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text)' }}>3. AI content — limitations and disclaimer</h2>
            <div className="rounded-xl p-4 mb-3" style={{ background: 'rgba(234,179,8,0.08)', border: '1px solid rgba(234,179,8,0.3)' }}>
              <p className="inline-flex items-center gap-2 font-medium mb-1" style={{ color: 'var(--text)' }}><IconAlert size={14} /> AI-generated content</p>
              <p>
                The Veritas Consolidated Article and bias analyses are automatically generated by AI models (Claude by Anthropic). Such content may contain inaccuracies, omissions, or errors. Lens Veritas does not warrant the accuracy, completeness, or timeliness of AI analyses. Do not rely on this information as the sole source for important decisions.
              </p>
            </div>
            <p>
              Pursuant to Art. 50(2) of the EU Regulation on Artificial Intelligence (EU AI Act), AI-generated content is marked as such within the site interface.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text)' }}>4. Intellectual property and copyright</h2>
            <p className="mb-2">
              Aggregated articles remain the property of their respective news outlets. Lens Veritas displays excerpts and headlines for informational purposes, with a direct link to the original source, in compliance with the right of quotation under Art. 70 of Italian Law 633/1941 (Italian Copyright Act) and EU Directive 2019/790.
            </p>
            <p>
              If you hold rights over content displayed on Lens Veritas and believe there is an infringement, please consult our <a href="/en/copyright" className="underline" style={{ color: 'var(--accent)' }}>copyright notice procedure</a>.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text)' }}>5. Acceptable use</h2>
            <p className="mb-2">By using Lens Veritas you agree not to:</p>
            <ul className="space-y-1 list-disc list-inside">
              <li>Perform automated scraping of the site&apos;s content</li>
              <li>Use the service for illegal activities or in violation of third-party rights</li>
              <li>Attempt to access unauthorised systems or data</li>
              <li>Distribute or publish the AI analyses as if produced by human journalists without disclosing their origin</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text)' }}>6. Limitation of liability</h2>
            <p>
              Lens Veritas is provided &quot;as is&quot; without warranties of any kind. The operator is not liable for any direct or indirect damages arising from use of the service, reliance on AI content, or temporary unavailability of the service.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text)' }}>7. Governing law and jurisdiction</h2>
            <p>
              These Terms are governed by Italian law. For any dispute the Court of Treviso (Italy) shall have exclusive jurisdiction (<em>foro competente</em>).
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: 'var(--text)' }}>8. Contact</h2>
            <p>
              For any matter regarding these Terms, write to{' '}
              <a href="mailto:paolo_fantinel@hotmail.com" className="underline" style={{ color: 'var(--accent)' }}>
                paolo_fantinel@hotmail.com
              </a>.
            </p>
          </section>

        </div>

        <div className="mt-12 pt-6 flex items-center justify-between text-xs" style={{ borderTop: '1px solid var(--border)', color: 'var(--text-3)' }}>
          <span>Lens Veritas · {LAST_UPDATED}</span>
          <a href="/" className="hover:opacity-80" style={{ color: 'var(--accent)' }}>← Back to home</a>
        </div>

      </div>
    </PageLayout>
  )
}
